name: decimal_for_cpp

on: [push]

jobs:
  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev

      - name: Build c++11
        run: |
          cd ${{ github.workspace }}
          mkdir -p b
          cd b
          cmake -DCMAKE_CXX_STANDARD=11 ../
          make && ./test_runner

      - name: Build c++14
        run: |
          cd ${{ github.workspace }}
          mkdir -p b
          cd b
          cmake -DCMAKE_CXX_STANDARD=14 ../
          make && ./test_runner

      - name: Build c++17
        run: |
          cd ${{ github.workspace }}
          mkdir -p b
          cd b
          cmake -DCMAKE_CXX_STANDARD=17 ../
          make && ./test_runner
